# Generated by Django 4.2 on 2026-01-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_endereco_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sigtap', models.CharField(help_text='Ex: 04.07.01.012-0', max_length=20, unique=True, verbose_name='Código SIGTAP')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do procedimento em reais', max_digits=10, verbose_name='Valor (R$)')),
                ('tipo_cirurgia', models.CharField(choices=[('ELETIVA', 'Eletiva'), ('URGENCIA', 'Urgência'), ('EMERGENCIA', 'Emergência'), ('AMBULATORIAL', 'Ambulatorial')], default='ELETIVA', max_length=20, verbose_name='Tipo de Cirurgia')),
                ('especialidade', models.CharField(help_text='Ex: Ortopedia, Cardiologia, etc.', max_length=100, verbose_name='Especialidade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
                'ordering': ['especialidade', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sigtap', models.CharField(help_text='Ex: 02.02.03.004-0', max_length=20, unique=True, verbose_name='Código SIGTAP')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do exame em reais', max_digits=10, verbose_name='Valor (R$)')),
                ('tipo_exame', models.CharField(choices=[('LABORATORIAL', 'Laboratorial'), ('IMAGEM', 'Imagem'), ('FUNCIONAL', 'Funcional'), ('PATOLOGIA', 'Patologia')], default='LABORATORIAL', max_length=20, verbose_name='Tipo de Exame')),
                ('preparo', models.TextField(blank=True, help_text='Orientações de preparo para o exame', verbose_name='Preparo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['tipo_exame', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sigtap', models.CharField(help_text='Ex: 03.01.01.007-5', max_length=20, unique=True, verbose_name='Código SIGTAP')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do serviço em reais', max_digits=10, verbose_name='Valor (R$)')),
                ('especialidade', models.CharField(blank=True, help_text='Especialidade responsável pelo serviço', max_length=100, verbose_name='Especialidade')),
                ('duracao_estimada', models.IntegerField(blank=True, help_text='Tempo estimado do atendimento em minutos', null=True, verbose_name='Duração Estimada (minutos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Serviço Médico',
                'verbose_name_plural': 'Serviços Médicos',
                'ordering': ['especialidade', 'descricao'],
            },
        ),
    ]
