# Generated by Django 4.2.27 on 2026-01-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cirurgia_tipo_cirurgia'),
        ('core', '0005_alter_usuario_managers_alter_usuario_username'),
    ]

    operations = [
    ]
